/** @file SNN Playground configuration constants. */

/** 
 * Radius for drawing regular neurons.
 * @type {number} 
 */
export const NEURON_RADIUS = 10;

/** 
 * Membrane potential threshold for a neuron to fire.
 * @type {number} 
 */
export const SPIKE_THRESHOLD = 1.0;

/** 
 * Rate at which a neuron's potential leaks over time.
 * @type {number} 
 */
export const LEAK_RATE = 0.01;

/** 
 * Duration (in milliseconds) for which a neuron cannot fire again after firing.
 * @type {number} 
 */
export const REFRACTORY_PERIOD = 50; // ms

/** 
 * Default strength of an incoming spike to a regular neuron.
 * @type {number} 
 */
export const INPUT_SPIKE_STRENGTH = 0.2;

/** 
 * Radius for drawing input nodes.
 * @type {number} 
 */
export const INPUT_NODE_RADIUS = 8;

/** 
 * Color for drawing inactive input nodes.
 * @type {string} 
 */
export const INPUT_NODE_COLOR_INACTIVE = 'lightgray';

/** 
 * Color for drawing active input nodes.
 * @type {string} 
 */
export const INPUT_NODE_COLOR_ACTIVE = 'limegreen';

/** 
 * Strength of spikes generated by input nodes.
 * @type {number} 
 */
export const INPUT_NODE_SPIKE_STRENGTH = 0.3;

/** 
 * Padding around each brain's drawing area on the main canvas.
 * @type {number} 
 */
export const BRAIN_CANVAS_PADDING = 10;

/** 
 * Default number of regular neurons to initialize per brain.
 * @type {number} 
 */
export const DEFAULT_NUM_NEURONS_PER_BRAIN = 5;

/** 
 * Default number of input nodes to initialize per brain.
 * @type {number} 
 */
export const DEFAULT_NUM_INPUT_NODES_PER_BRAIN = 2;
