// === Modern Test Suite using AutoTestGen ===

// Load all modules
const autoTest = new AutoTestGen();

// === Auto-Discovery and Generation ===
function runAutoGeneratedTests() {
  console.log('🤖 Running Auto-Generated Tests...');
  
  // Check if AI is enabled for enhanced testing
  if (forge.aiConfig.enabled) {
    console.log('🧠 AI-Enhanced mode detected - generating smarter tests...');
  }
  
  // Auto-discover and test all functions
  autoTest
    .autoDiscover(window)
    .run()
    .then(results => {
      console.log('🎉 Auto-generation complete!');
      displayResults();
    });
}

// === Manual Test Definition with Fluent API ===
function runFluentAPITests() {
  console.log('💫 Running Fluent API Tests...');
  
  // Log AI status
  const aiStatus = forge.aiConfig.enabled ? 'with AI assistance' : 'with rule-based analysis';
  console.log(`🔬 Running ${aiStatus}...`);
  
  // Modern fluent test definition
  autoTest
    .describe('Greet Function')
    .test('should greet properly', () => {
      autoTest.describe('Greet Function').expect(greet('John')).toBe('Hello, John!');
    })
    .test('should handle whitespace', () => {
      autoTest.describe('Greet Function').expect(greet('  Jane  ')).toBe('Hello, Jane!');
    })
    .test('should throw for invalid input', () => {
      autoTest.describe('Greet Function').expect(() => greet(null)).toThrow('Name is required');
    });

  autoTest
    .describe('Math Operations')
    .test('division should work', () => {
      autoTest.describe('Math Operations').expect(divide(10, 2)).toBe(5);
    })
    .test('should reject string inputs', () => {
      autoTest.describe('Math Operations').expect(() => divide('10', '2')).toThrow('must be numbers');
    })
    .property('should be associative', 
      () => ({ a: Math.random() * 100, b: Math.random() * 10 + 1 }),
      ({ a, b }) => {
        const result = divide(a, b);
        autoTest.describe('Math Operations').expect(typeof result).toBe('number');
        autoTest.describe('Math Operations').expect(result).toBe(a / b);
      }
    );

  autoTest.run();
}

// === Property-Based Testing Example ===
function runPropertyBasedTests() {
  console.log('🎲 Running Property-Based Tests...');
  
  autoTest
    .describe('Property Tests')
    .property('greet always returns string starting with Hello',
      () => `TestUser${Math.floor(Math.random() * 1000)}`,
      (name) => {
        const result = greet(name);
        autoTest.describe('Property Tests').expect(result).toBeType('string');
        autoTest.describe('Property Tests').expect(result).toMatch(/^Hello, .+!$/);
      }
    )
    .property('division is inverse of multiplication',
      () => ({ 
        a: Math.floor(Math.random() * 100) + 1, 
        b: Math.floor(Math.random() * 10) + 1 
      }),
      ({ a, b }) => {
        const divided = divide(a, b);
        const multiplied = divided * b;
        autoTest.describe('Property Tests').expect(Math.abs(multiplied - a)).toBeLessThan(0.0001);
      }
    );

  autoTest.run();
}

// === Legacy Test Functions (keeping for backwards compatibility) ===
function runBasicTests() {
  testResults = ['🔥 Running Basic Tests with Legacy Framework...', ''];
  
  // Happy path tests
  test("greet('Justinas') should return 'Hello, Justinas!'", () => {
    assertEqual(greet("Justinas"), "Hello, Justinas!");
  });
  
  test("divide(10, 2) should return 5", () => {
    assertEqual(divide(10, 2), 5);
  });
  
  test("calculateAverage([1, 2, 3]) should return 2", () => {
    assertEqual(calculateAverage([1, 2, 3]), 2);
  });
  
  displayResults();
}

function runEdgeCaseTests() {
  testResults = ['⚠️ Running Edge Case Tests with Legacy Framework...', ''];
  
  // Null/undefined tests
  test("greet() with no argument should throw error", () => {
    assertThrows(() => greet(), 'Name is required');
  });
  
  test("greet(null) should throw error", () => {
    assertThrows(() => greet(null), 'Name is required');
  });
  
  // Type validation tests
  test("greet(123) should throw error for non-string", () => {
    assertThrows(() => greet(123), 'Name must be a string');
  });
  
  test("divide('5', '2') should throw error for non-numbers", () => {
    assertThrows(() => divide('5', '2'), 'Both arguments must be numbers');
  });
  
  // Boundary tests
  test("divide by zero should throw error", () => {
    assertThrows(() => divide(10, 0), 'Cannot divide by zero');
  });
  
  test("calculateAverage([]) should throw error for empty array", () => {
    assertThrows(() => calculateAverage([]), 'Array cannot be empty');
  });
  
  test("calculateAverage with non-numbers should throw error", () => {
    assertThrows(() => calculateAverage([1, 'hello', 3]), 'All elements must be valid numbers');
  });
  
  // Whitespace handling
  test("greet('  Justinas  ') should handle whitespace", () => {
    assertEqual(greet("  Justinas  "), "Hello, Justinas!");
  });
  
  displayResults();
}

function runComplexTests() {
  testResults = ['🎯 Running Complex Scenario Tests with Legacy Framework...', ''];
  
  // User creation tests
  test("createUser with valid data should succeed", () => {
    const user = createUser("John Doe", 25, "john@example.com");
    assertEqual(user.name, "John Doe");
    assertEqual(user.age, 25);
    assertEqual(user.email, "john@example.com");
  });
  
  test("createUser with invalid age should throw error", () => {
    assertThrows(() => createUser("John", -5, "john@example.com"), 'Age must be between 0 and 150');
  });
  
  test("createUser with invalid email should throw error", () => {
    assertThrows(() => createUser("John", 25, "invalid-email"), 'Email must be a valid email address');
  });
  
  // Password strength tests
  test("weak password should return weak strength", () => {
    const result = checkPasswordStrength("123");
    assertEqual(result.strength, "weak");
    assert(result.score < 2, "Weak password should have score < 2");
  });
  
  test("strong password should return strong strength", () => {
    const result = checkPasswordStrength("MyStr0ng!Pass");
    assertEqual(result.strength, "strong");
    assert(result.score >= 4, "Strong password should have score >= 4");
  });
  
  test("password with all criteria should get max score", () => {
    const result = checkPasswordStrength("SuperStr0ng!Password123");
    assertEqual(result.strength, "strong");
    assertEqual(result.score, 5);
  });
  
  // Complex mathematical edge cases
  test("calculateAverage with very large numbers", () => {
    const result = calculateAverage([1000000, 2000000, 3000000]);
    assertEqual(result, 2000000);
  });
  
  test("calculateAverage with decimals", () => {
    const result = calculateAverage([1.5, 2.5, 3.0]);
    assertEqual(result, 2.333333333333333);
  });
  
  displayResults();
}

function runAllTests() {
  console.log('🚀 Running ALL Tests - Modern + Legacy');
  
  // Run modern tests
  Promise.all([
    runAutoGeneratedTests(),
    runFluentAPITests(),
    runPropertyBasedTests()
  ]).then(() => {
    // Then run legacy tests
    testResults = ['📊 Legacy Test Results:', ''];
    
    // Track statistics
    let totalTests = 0;
    let passedTests = 0;
    
    const runTestSuite = (suiteName, testFunctions) => {
      testResults.push(`\n📋 ${suiteName}:`);
      testFunctions.forEach(testFn => {
        totalTests++;
        if (testFn()) passedTests++;
      });
    };
    
    // Test function collections
    const basicTestFunctions = [
      () => test("greet('Justinas') should return 'Hello, Justinas!'", () => {
        assertEqual(greet("Justinas"), "Hello, Justinas!");
      }),
      () => test("divide(10, 2) should return 5", () => {
        assertEqual(divide(10, 2), 5);
      }),
      () => test("calculateAverage([1, 2, 3]) should return 2", () => {
        assertEqual(calculateAverage([1, 2, 3]), 2);
      })
    ];
    
    const edgeTestFunctions = [
      () => test("greet() with no argument should throw error", () => {
        assertThrows(() => greet(), 'Name is required');
      }),
      () => test("divide by zero should throw error", () => {
        assertThrows(() => divide(10, 0), 'Cannot divide by zero');
      }),
      () => test("calculateAverage([]) should throw error for empty array", () => {
        assertThrows(() => calculateAverage([]), 'Array cannot be empty');
      }),
      () => test("greet with non-string should throw error", () => {
        assertThrows(() => greet(123), 'Name must be a string');
      }),
      () => test("divide with non-numbers should throw error", () => {
        assertThrows(() => divide('5', '2'), 'Both arguments must be numbers');
      })
    ];
    
    const integrationTestFunctions = [
      () => test("createUser with valid data should succeed", () => {
        const user = createUser("John Doe", 25, "john@example.com");
        assertEqual(user.name, "John Doe");
        assertEqual(user.age, 25);
        assertEqual(user.email, "john@example.com");
      }),
      () => test("strong password validation works correctly", () => {
        const result = checkPasswordStrength("MyStr0ng!Pass");
        assertEqual(result.strength, "strong");
        assert(result.score >= 4);
      }),
      () => test("createUser with multiple validation errors", () => {
        assertThrows(() => createUser("", -5, "bad-email"), 'Name must be a non-empty string');
      }),
      () => test("password strength handles edge cases", () => {
        const weakResult = checkPasswordStrength("123");
        assertEqual(weakResult.strength, "weak");
        
        const invalidResult = checkPasswordStrength(null);
        assertEqual(invalidResult.strength, "invalid");
      })
    ];
    
    // Run all test suites
    runTestSuite("Basic Functionality", basicTestFunctions);
    runTestSuite("Edge Cases", edgeTestFunctions);
    runTestSuite("Integration Tests", integrationTestFunctions);
    
    // Generate comprehensive summary
    testResults.push(`\n📊 Test Summary:`);
    testResults.push(`   Total Tests: ${totalTests}`);
    testResults.push(`   Passed: ${passedTests}`);
    testResults.push(`   Failed: ${totalTests - passedTests}`);
    testResults.push(`   Success Rate: ${((passedTests / totalTests) * 100).toFixed(1)}%`);
    
    if (passedTests === totalTests) {
      testResults.push(`\n🎉 All tests passed! You're a testing champion! 🏆`);
      testResults.push(`\n🎓 Pro Tip: Now try adding more complex scenarios!`);
    } else {
      testResults.push(`\n🔧 Some tests failed. Time to debug and improve! 💪`);
      testResults.push(`\n🎯 Focus on fixing the failing tests one by one.`);
    }
    
    displayResults();
  });
}

// === New Test Runner Functions ===
window.runAutoGeneratedTests = runAutoGeneratedTests;
window.runFluentAPITests = runFluentAPITests;
window.runPropertyBasedTests = runPropertyBasedTests;

// === Initialize ===
console.log("🤖 AutoTestGen Framework Loaded!");
console.log("🎯 Available: Auto-generation, Property-based testing, Fluent API");
console.log("💡 Configure AI provider for enhanced analysis and suggestions!");
console.log("🔑 API Key Status:", forge.aiConfig.connected ? "Connected ✅" : "Not Connected ❌");
